### ISSUE TITLE
Automatic ACRE channels

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARC_MF.VR#2]
Why do we have to set these up manually? Automation is the future, let the game play itself..

**Comment by CER10TY** [comment]
You mean automatically setting channels for certain members? Ie. members in Alpha 2 automatically get 343 Channel 2 etc.

**Comment by jameslkingsley** [comment]
Yeah exactly what I was thinking, it'll just make things so much easier.

**Comment by CER10TY** [comment]
Should be really simple to throw it into one of the existing files, I'll have a look at it

**Comment by jameslkingsley** [comment]
I'm implementing a comm plan section on the map that should outline what radio channels each group has. So there should be two pages one showing the "tree" view of the platoon and the other showing some links to do the add radios stuff just in case.

**Comment by jameslkingsley** [comment]
There's going to be too much overhead to implement this since you'd have to setup what radios and channels each group has so for adding groups it's just going to be a pain.
