### ISSUE TITLE
Group class structure

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARC_MF.VR#4]
The current group class structure is a bit long and it could be a pain to expand it in the future. There needs to be a very efficient way of structuring the groups so that we have a universal class to be used in the platoon roster, comm plan, map markers etc. I'm not too sure how to properly structure this since I don't really want to have hard coded groups since adding groups in the future would be a lot of work and if a mission maker wants a custom group that's not there it could be quite difficult for them to implement.

**Comment by CER10TY** [comment]
Are you talking about GrpNATO_XX structure? Personally don't see a more efficient way of doing it since all groups need unique identifiers.

**Comment by jameslkingsley** [comment]
No that's the part which is fine, it's how you sort those groups for roster and stuff. Look at my latest commit it should show a group class with some stuff.
